export const categoryMap = {
  map: 'Mapping and Sequencing',
  genes: 'Genes and Gene Predictions',
  phenDis: 'Phenotypes, Variants, and Literature',
  rep: 'Repeats',
  varRep: 'Variation and Repeats',
  rna: 'mRNA and EST',
  neandertal: 'Neandertal Assembly and Analysis',
  denisova: 'Denisova Assembly and Analysis',
  expression: 'Expression',
  compGeno: 'Comparative Genomics',
  regulation: 'Regulation',
  singleCell: 'Single cell',
  hprc: 'Human Pangenome',
}
